# Generated by Django 5.1.5 on 2025-02-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqapp', '0005_audience_device_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closed_request', to='reqapp.request')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenOffDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_off_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='written_off_device', to='reqapp.device')),
            ],
        ),
    ]
