version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn yourproject.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DATABASE_URL: postgres://django_user:secretpassword@db:5432/django_db
      DJANGO_SECRET_KEY: your-secret-key-123
      DJANGO_DEBUG: "False"
    depends_on:
      - db
    ports:
      - "8000:8000"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - web
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123

volumes:
  postgres_data:
  grafana_data: